version: "3.8"
services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: spacex
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    command: --log_error_verbosity=1
  spacex:
    image: corkyahern662/spacex
    container_name: spacex
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: always
    ports:
      - 8080:8080
